
-- ----------------------------
-- Triggers structure for table DS_SCHEDULE_JOB_INFO
-- ----------------------------
CREATE OR REPLACE TRIGGER "ZHFT123"."TRIGGER_DS_SCHEDULE_JOB_INFO" BEFORE INSERT ON "ZHFT123"."DS_SCHEDULE_JOB_INFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
BEGIN
  SELECT SEQ_DS_SCHEDULE_JOB_INFO.NEXTVAL INTO :NEW.ID FROM DUAL;
END TRIGGER_DS_SCHEDULE_JOB_INFO;

-- ----------------------------
-- Triggers structure for table DS_SYNCH_JOB_LOG_INFO
-- ----------------------------
CREATE OR REPLACE TRIGGER "ZHFT123"."TRIGGER_DS_SYNCH_JOB_LOG_INFO" BEFORE INSERT ON "ZHFT123"."DS_SYNCH_JOB_LOG_INFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
BEGIN
  SELECT SEQ_DS_SYNCH_JOB_LOG_INFO.NEXTVAL INTO :NEW.ID FROM DUAL;
END TRIGGER_DS_SYNCH_JOB_LOG_INFO;

-- ----------------------------
-- Triggers structure for table DS_COLUMN_MAPPING_INFO
-- ----------------------------
CREATE OR REPLACE TRIGGER "ZHFT123"."TRIGGER_DS_COLUMN_MAPPING_INFO" BEFORE INSERT ON "ZHFT123"."DS_COLUMN_MAPPING_INFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
BEGIN
  SELECT SEQ_DS_COLUMN_MAPPING_INFO.NEXTVAL INTO :NEW.ID FROM DUAL;
END TRIGGER_DS_COLUMN_MAPPING_INFO;
