/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : ZHFT123
Source Server Version : 110200
Source Host           : localhost:1521
Source Schema         : ZHFT123

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2018-10-11 17:07:48
*/
--创建序列
create sequence SEQ_DS_SCHEDULE_JOB_INFO
minvalue 1
maxvalue 99999999
start with 1
increment by 1
cache 50;

create sequence SEQ_DS_SYNCH_JOB_LOG_INFO
minvalue 1
maxvalue 99999999
start with 1
increment by 1
cache 50;

create sequence SEQ_DS_COLUMN_MAPPING_INFO
minvalue 1
maxvalue 99999999
start with 1
increment by 1
cache 50;
---
-- ----------------------------
-- Table structure for DS_SCHEDULE_JOB_INFO
-- ----------------------------
DROP TABLE "ZHFTYJJCPT"."DS_SCHEDULE_JOB_INFO";
CREATE TABLE "ZHFTYJJCPT"."DS_SCHEDULE_JOB_INFO" (
"ID" NUMBER NULL ,
"CONN_TYPE" NUMBER NULL ,
"SOURCE" VARCHAR2(1024 BYTE) NULL ,
"TB_NAME" VARCHAR2(255 BYTE) NULL ,
"SCHEDULE_EXPRESSION" VARCHAR2(255 BYTE) NULL ,
"IS_ENABLED" NUMBER NULL ,
"CREATE_TIME" DATE DEFAULT sysdate  NULL ,
"UPDATE_TIME" DATE NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SCHEDULE_JOB_INFO"."ID" IS '自增主键';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SCHEDULE_JOB_INFO"."CONN_TYPE" IS '连接方式(0：前置机方式 1：接口方式)';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SCHEDULE_JOB_INFO"."SOURCE" IS '源(请求URL路径/前置机view视图的名称)';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SCHEDULE_JOB_INFO"."TB_NAME" IS '入库表名';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SCHEDULE_JOB_INFO"."SCHEDULE_EXPRESSION" IS '定时表达式';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SCHEDULE_JOB_INFO"."IS_ENABLED" IS '是否开启（0：关闭 1：开启）';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SCHEDULE_JOB_INFO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SCHEDULE_JOB_INFO"."UPDATE_TIME" IS '更新时间';

-- ----------------------------
-- Triggers structure for table DS_SCHEDULE_JOB_INFO
-- ----------------------------
CREATE OR REPLACE TRIGGER "ZHFTYJJCPT"."TRIGGER_DS_SCHEDULE_JOB_INFO" BEFORE INSERT ON "ZHFTYJJCPT"."DS_SCHEDULE_JOB_INFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
BEGIN
  SELECT SEQ_DS_SCHEDULE_JOB_INFO.NEXTVAL INTO :NEW.ID FROM DUAL;
END TRIGGER_DS_SCHEDULE_JOB_INFO;



-- ----------------------------
-- Table structure for DS_SYNCH_JOB_LOG_INFO
-- ----------------------------
DROP TABLE "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO";
CREATE TABLE "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO" (
"ID" NUMBER NULL ,
"JOBID" NUMBER NULL ,
"CURRENT_PAGE" NUMBER NULL ,
"CURRENT_ROWNUM" NUMBER NULL ,
"UPDATE_WAY" NUMBER NULL ,
"CREATE_TIME" DATE DEFAULT sysdate  NULL ,
"UPDATE_TIME" DATE NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."ID" IS '唯一主键';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."JOBID" IS '关联任务ID';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."CURRENT_PAGE" IS '当前请求页码';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."CURRENT_ROWNUM" IS '当前页最后一条数据的分页查询伪ID';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."UPDATE_WAY" IS '更新方式（0：数据库 1：接口）';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."UPDATE_TIME" IS '更新时间';

-- ----------------------------
-- Records of DS_SYNCH_JOB_LOG_INFO
-- ----------------------------

-- ----------------------------
-- Triggers structure for table DS_SYNCH_JOB_LOG_INFO
-- ----------------------------
CREATE OR REPLACE TRIGGER "ZHFTYJJCPT"."TRIGGER_DS_SYNCH_JOB_LOG_INFO" BEFORE INSERT ON "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
BEGIN
  SELECT SEQ_DS_SYNCH_JOB_LOG_INFO.NEXTVAL INTO :NEW.ID FROM DUAL;
END TRIGGER_DS_SYNCH_JOB_LOG_INFO;





-- ----------------------------
-- Table structure for DS_COLUMN_MAPPING_INFO
-- ----------------------------
DROP TABLE "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO";
CREATE TABLE "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO" (
"ID" NUMBER NULL ,
"TAGET_TABLE" VARCHAR2(255 BYTE) NULL ,
"SOURCE" VARCHAR2(255 BYTE) NULL ,
"SRC_COLUMN_NAME" VARCHAR2(255 BYTE) NULL ,
"TARGET_COLUMN_NAME" VARCHAR2(255 BYTE) NULL ,
"CREATE_TIME" DATE DEFAULT sysdate  NULL ,
"UPDATE_TIME" DATE NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO"."ID" IS '唯一主键';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO"."TAGET_TABLE" IS '目标表名称';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO"."SOURCE" IS '源表名称/源URL';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO"."SRC_COLUMN_NAME" IS '源字段名称';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO"."UPDATE_TIME" IS '修改时间';

-- ----------------------------
-- Triggers structure for table DS_COLUMN_MAPPING_INFO
-- ----------------------------
CREATE OR REPLACE TRIGGER "ZHFTYJJCPT"."TRIGGER_DS_COLUMN_MAPPING_INFO" BEFORE INSERT ON "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
BEGIN
  SELECT SEQ_DS_COLUMN_MAPPING_INFO.NEXTVAL INTO :NEW.ID FROM DUAL;
END TRIGGER_DS_COLUMN_MAPPING_INFO;