/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : ZHFTYJJCPT_local
Source Server Version : 110200
Source Host           : 10.192.19.108:1521
Source Schema         : ZHFTYJJCPT

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2018-11-12 15:03:16
*/


-- ----------------------------
-- Table structure for DS_COLUMN_MAPPING_INFO
-- ----------------------------
DROP TABLE "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO";
CREATE TABLE "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO" (
"ID" NUMBER NULL ,
"TARGET_TABLE" VARCHAR2(255 BYTE) NULL ,
"SOURCE" VARCHAR2(255 BYTE) NULL ,
"SRC_COLUMN_NAME" VARCHAR2(255 BYTE) NULL ,
"TARGET_COLUMN_NAME" VARCHAR2(255 BYTE) NULL ,
"CREATE_TIME" DATE DEFAULT sysdate  NULL ,
"UPDATE_TIME" DATE DEFAULT sysdate  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO"."ID" IS '唯一主键';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO"."TARGET_TABLE" IS '目标表名称';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO"."SOURCE" IS '源表名称/源URL';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO"."SRC_COLUMN_NAME" IS '源字段名称';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_COLUMN_MAPPING_INFO"."UPDATE_TIME" IS '修改时间';
