/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : ZHFTYJJCPT_local
Source Server Version : 110200
Source Host           : 10.192.19.108:1521
Source Schema         : ZHFTYJJCPT

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2018-11-12 15:03:39
*/


-- ----------------------------
-- Table structure for DS_SYNCH_JOB_LOG_INFO
-- ----------------------------
DROP TABLE "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO";
CREATE TABLE "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO" (
"ID" NUMBER NULL ,
"JOBID" NUMBER NULL ,
"IS_SUCCESS" NUMBER NULL ,
"QUERY_RESULT_SIZE" NUMBER NULL ,
"CURRENT_PAGE_NUM" NUMBER NULL ,
"CURRENT_PAGE_SIZE" NUMBER NULL ,
"START_ROW" NUMBER NULL ,
"END_ROW" NUMBER NULL ,
"CONN_TYPE" NUMBER NULL ,
"SUCCESS_COUNT" NUMBER NULL ,
"FAIL_COUNT" NUMBER NULL ,
"TOTAL_SUCCESS_COUNT" NUMBER NULL ,
"TOTAL_FAIL_COUNT" NUMBER NULL ,
"CREATE_TIME" DATE DEFAULT sysdate  NULL ,
"UPDATE_TIME" DATE DEFAULT sysdate  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."ID" IS '唯一主键';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."JOBID" IS '关联任务ID';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."IS_SUCCESS" IS '本次是否成功';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."QUERY_RESULT_SIZE" IS '本次请求包大小';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."CURRENT_PAGE_NUM" IS '当前请求页码';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."CURRENT_PAGE_SIZE" IS '当前页大小';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."START_ROW" IS '本次请求起始行';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."END_ROW" IS '本次请求结束行（包含）';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."CONN_TYPE" IS '更新方式（0：数据库 1：接口）';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."SUCCESS_COUNT" IS '本次成功插入条数';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."FAIL_COUNT" IS '本次失败插入条数';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."TOTAL_SUCCESS_COUNT" IS '总成功数';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."TOTAL_FAIL_COUNT" IS '总失败数';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "ZHFTYJJCPT"."DS_SYNCH_JOB_LOG_INFO"."UPDATE_TIME" IS '更新时间';
